import { StyleSheet } from "react-native";
import { colors } from "../../components/ui";

export const styles = StyleSheet.create({
  clearHistory: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    minHeight: 44,
    gap: 7,
    paddingHorizontal: 6,
  },
  screen: { flex: 1, backgroundColor: colors.paper },
  header: {
    paddingHorizontal: 10,
    paddingBottom: 17,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
  },
  headerRow: { flexDirection: "row", alignItems: "center", gap: 2 },
  iconButton: {
    width: 44,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: "#FFF",
    lineHeight: 27,
  },
  headerSubtitle: { fontSize: 12, color: "#D5E6DC", lineHeight: 19 },
  conversation: { padding: 20, gap: 16, paddingBottom: 24 },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 30,
  },
  welcome: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 12,
    paddingBottom: 8,
  },
  emblem: {
    width: 80,
    height: 80,
    borderRadius: 28,
    backgroundColor: colors.dark,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  eyebrow: {
    color: colors.gold,
    letterSpacing: 1.8,
    fontSize: 10,
    fontWeight: "700",
    marginBottom: 10,
  },
  welcomeTitle: {
    fontSize: 27,
    lineHeight: 35,
    letterSpacing: -0.7,
    fontWeight: "700",
    color: colors.ink,
    textAlign: "center",
  },
  welcomeBody: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.muted,
    textAlign: "center",
    maxWidth: 310,
    marginTop: 12,
  },
  suggestions: { gap: 10, alignSelf: "stretch", marginTop: 28 },
  suggestion: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    padding: 14,
  },
  suggestionIcon: {
    width: 38,
    height: 42,
    borderRadius: 13,
    backgroundColor: colors.light,
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 21,
  },
  suggestionQuestion: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  message: { borderRadius: 22, padding: 17, gap: 12, maxWidth: "94%" },
  userMessage: {
    alignSelf: "flex-end",
    backgroundColor: colors.green,
    borderBottomRightRadius: 6,
  },
  assistantMessage: {
    alignSelf: "flex-start",
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: colors.line,
    borderTopLeftRadius: 6,
  },
  author: {
    color: colors.green,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
  },
  messageText: { color: colors.ink, fontSize: 15, lineHeight: 25 },
  guidanceNote: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 12,
    gap: 6,
  },
  thinking: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    paddingVertical: 10,
  },
  composerArea: {
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.paper,
    gap: 8,
  },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    padding: 7,
    borderWidth: 1,
    borderColor: "#CBD9CB",
    borderRadius: 26,
    backgroundColor: "#FFF",
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 124,
    paddingHorizontal: 11,
    paddingTop: 11,
    paddingBottom: 11,
    fontSize: 15,
    lineHeight: 22,
    color: colors.ink,
  },
  send: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
  },
  disclaimer: {
    fontSize: 10,
    lineHeight: 15,
    color: colors.muted,
    textAlign: "center",
  },
  counter: { fontSize: 11, color: colors.muted, textAlign: "right" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(16,61,45,0.4)",
    justifyContent: "flex-end",
  },
  sheet: {
    height: "78%",
    backgroundColor: colors.paper,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    gap: 14,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    backgroundColor: "#CBD9CB",
    borderRadius: 2,
    alignSelf: "center",
  },
  close: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
});
